### ISSUE TITLE
Broadcast message

### ISSUE THREAD

**Issue by Saturn745** [apteryxxyz/next-ws#1]
How would one broadcast a message to all clients using this library? The websocket library shows https://github.com/websockets/ws#server-broadcast but I cannot seem to do it using next-ws, unless I am missing something?

**Comment by apteryxxyz** [comment]
`next-ws` doesn't expose the `WebSocketServer` it creates, so currently you are unable to access `wss.clients`. I suppose I could pass the server as the third parameter of the `SOCKET` function

**Comment by apteryxxyz** [comment]
I just published version 0.1.4 which adds the `WebSocketServer` as the third parameter of `SOCKET`, let me know how it goes then this can be closed.

```ts
export function SOCKET(
    client: import('ws').WebSocket,
    request: import('http').IncomingMessage,
    server: import('ws').WebSocketServer,
) {
    // ...
}
```

**Comment by Saturn745** [comment]
I updated the library and it seems only the README and package.json got published.

**Comment by apteryxxyz** [comment]
> I updated the library and it seems only the README and package.json got published.

Oops, okay I'll fix that, looks like `yarn pack` and `npm pack` have different outputs

**Comment by apteryxxyz** [comment]
Should be good now with 0.1.5.

**Comment by Saturn745** [comment]
Thanks! It works great.
