### ISSUE TITLE
Persistence and multi instance setup

### ISSUE THREAD

**Issue by gsogol** [apteryxxyz/next-ws#10]
Thank you for your work. 

1) looks like this doesn't work with the latest nextjs version. Not sure what the issue is :(
2) how are messages persisted? For example socket.io can persist in redis or postgres. what happens when a client reconnects and connects to a new instance (assuming multiple backend instances are running)?

🙏

**Comment by apteryxxyz** [comment]
1. As far as I can tell it still works
![image](https://github.com/apteryxxyz/next-ws/assets/40654585/23ebb710-8da5-4d6b-9c06-7b0e820bcd4a)

2. The purpose of this package is to just expose a way to receive WebSocket connections in the app router using the NPM package `ws`, anything else is out of scope for this package.
