### ISSUE TITLE
Next.js v14.1.0

### ISSUE THREAD

**Issue by enex** [apteryxxyz/next-ws#15]
Initially from the logs and `verifyPatch` it seamed to be working, however it does not detect the export SOCKET function on the route.

**Comment by apteryxxyz** [comment]
Do you happen to have a repro? As far as I can tell Next WS still works with 14.1.0.
![image](https://github.com/apteryxxyz/next-ws/assets/40654585/254cab65-5023-42d3-9774-5ef702ac1f0c)

**Comment by enex** [comment]
Thanks for your fast reply. I tried with a new npm based project and indeed it works fine. However if I switch to pnpm, as the original project uses it for package management, it does not work as expected. It tries to connect but remains in a pending state which for some reason is not the same error I got in the original project.
I also tried to apply the patch manually but it did not fix the issue https://github.com/enex/next-ws-test
So over all i think it has more todo with how pnpm work than with next.js

**Comment by apteryxxyz** [comment]
I cloned your repo, removed the pnpm patch, installed dependences with pnpm, ran `npx next-ws-cli@latest patch`, then started with `pnpm next dev`. Opening the web page it does successfully connect and send does work (get the message back). Does sound like an issue with how pnpm works, not really sure where to go to from here.

**Comment by enex** [comment]
Thanks for your effort, now i got it working in this repository too, so i can say for sure it has nothing todo with next 14.1 and something with pnpm. If I find out what it is I share it in this thread so others that may have the same problem can avoid it. Should the issue therefore be closed, renamed or something?

**Comment by enex** [comment]
The actual issue was something completely unrelated to pnpm. I have updated [my test repository](https://github.com/enex/next-ws-test) to reproduce it. The problem is that `resolvePathname` function assumes the first matching path must be where the `route` file exists, which is not always true. I also created a merge request with the change necessary to fix it. Unrelated but you could also probably increase the version number in CLI for the nextjs version check because it seems to work fine now. 👍🏻
