### ISSUE TITLE
Server not run

### ISSUE THREAD

**Issue by duchuy2707** [apteryxxyz/next-ws#22]
hi Apteryx

```
import * as ws from 'ws';

export function SOCKET(
  client: ws.WebSocket,
) {
  console.clear();
  console.log('\n--------\n', 'A client connected!', '\n--------\n');

  client.on('message', message => {
    client.send(message);
  });

  client.on('close', () => {
    console.log('A client disconnected!');
  });
}
```
I've tried to test as in the example to create a socket server like the code snippet below, but it seems it's not working. No console logs are appearing, and it seems like the code isn't being called. I'm using "next": "13.4.19" with app routes. 

If you have time, could you assist me, please? 
Thank you very much, and I wish you good health.

**Comment by apteryxxyz** [comment]
`next-ws` does not support `next@13.4.19`, you need `<=13.4.12` or `>=13.5.1`

**Comment by duchuy2707** [comment]
hi @apteryxxyz 
thank you for support <3
