### ISSUE TITLE
Error when having middleware.ts

### ISSUE THREAD

**Issue by Adrian11asd** [apteryxxyz/next-ws#33]
![image](https://github.com/apteryxxyz/next-ws/assets/72896911/7e40753a-50c3-4484-a6e1-db45433f74a9)
![image2](https://github.com/apteryxxyz/next-ws/assets/72896911/01d4e428-889a-4937-9a7a-7ff62405ea21)
As shown in the images, there is an error with .bind.

I've done some testing, making a new nextjs project.
in the brand new project the SOCKET endpoint works fine. The problem only happens when I have a middleware.ts file.
It happens even when middleware.ts is completely empty.

**Comment by apteryxxyz** [comment]
Related issue: #27 
You need to exclude your websocket route within your middleware config.
