### ISSUE TITLE
Error: Cannot find module `next-ws/client`

### ISSUE THREAD

**Issue by NriotHrreion** [apteryxxyz/next-ws#38]
## To Reproduce

```ts
import { useWebSocket } from "next-ws/client";
```

Then, get error:

```
There are types at 'node_modules/next-ws/dist/client/index.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.
```

## Description

I can solve this by setting `moduleResolution` from `esnext` to `node16` or `nodenext` in my tsconfig.json. But some of my installed packages will throw other type errors. So just open the issue to report this.

**Note:** Despite of the type error, the other functionality works well.

**Comment by apteryxxyz** [comment]
Change `moduleResolution` to `bundler`, since Next.js is the bundler.

**Comment by NriotHrreion** [comment]
solved
