### ISSUE TITLE
Websocket not working with react-spring

### ISSUE THREAD

**Issue by braveltd** [apteryxxyz/next-ws#39]
If you install pnpm add react-spring, websocket not starting and not working. idk what the reason is.
![image](https://github.com/user-attachments/assets/8ebd26a5-256e-4d58-bee7-c5765815c779)
as you can see,  after installing it websocket not starts.

**Comment by apteryxxyz** [comment]
After installing react-spring can you run `npx next-ws-cli@latest verify` and ensure `next` is still patched

**Comment by braveltd** [comment]
so ur telling i gotta repatch after any update?

> After installing react-spring can you run `npx next-ws-cli@latest verify` and ensure `next` is still patched

**Comment by braveltd** [comment]
IDK, probably i should just patched it. Great lib using it!
