### ISSUE TITLE
nextjs 15 support

### ISSUE THREAD

**Issue by farseekers** [apteryxxyz/next-ws#42]
nextjs 15 has been released - https://github.com/vercel/next.js/releases/tag/v15.0.0

When applying the patch, if I try and push past the warning
> [next-ws] Next WS has not yet been tested with Next.js v15.0.0, it may or may not work, are you sure you want to continue?

then when building I see
> "SOCKET" is not a valid Route export field.

leading to the conclusion that the patch needs to be updated. At your next convenience, would you be able to do so?

**Comment by braveltd** [comment]
Nextjs 15 just released, so i guess support for it will come soon. Rn nextjs 14.2.15 works fine for me!
Give the maintainer a week or so, and the support will be for it!

**Comment by apteryxxyz** [comment]
Oof, Next.js changed from using `"` to `'` which broke part of the patch, will be an easy fix and will release sometime today

**Comment by farseekers** [comment]
Thanks very much.

**Comment by braveltd** [comment]
Thank you!
