### ISSUE TITLE
How do I deploy this app.... 

### ISSUE THREAD

**Issue by Viclaww** [apteryxxyz/next-ws#48]
This is the link to my repo.. Everything works fine on local but server doest connect on deployment https://github.com/[Viclaww/deadandinjured](https://github.com/Viclaww/deadandinjured)

**Comment by apteryxxyz** [comment]
It appears you're trying to deploy to Vercel, as mentioned in the readme
![image](https://github.com/user-attachments/assets/6668cefc-9757-41e0-8f62-feae097ab673)
Where to host is your responsibility and I cannot help with that
