### ISSUE TITLE
Max supported Next.js version is 13.4.12

### ISSUE THREAD

**Issue by apteryxxyz** [apteryxxyz/next-ws#6]
In the v13.4.13 release of Next.js, something changed causing the `httpServer` `upgrade` event to no longer be triggered, which breaks this package. I spent a bit of time to try and fix it but there are a lot of changes between versions of Next.js so it is tough to determine what exact change caused this package to break. When I have time I will look deeper and do more testing, but until then if anyone knows how to fix it please let me know/open a pull request. Thanks.

**Comment by GGAlanSmithee** [comment]
@apteryxxyz just to let you know, there might have been some movement in the linked issue from Sept. 13 https://github.com/vercel/next.js/pull/57245

**Comment by apteryxxyz** [comment]
I've just released a new version that fixes this issue, there is a new patch with the range `>=13.5.1 <=14.0.1`.
